name = "workers-weather"
type = "javascript"

workers_dev = true  # Permite rodar sem domínio próprio
main = "src/index.js"  # Arquivo de entrada

# Configuração para produção (sem zone_id)
[env.production]
route = "weather.alicinomoura.xyz/*"

