name = "cloudflare-weather-worker"
type = "javascript"

account_id = "ACCOUNT_ID"
workers_dev = true  # Permite rodar sem domínio próprio
main = "src/index.js"  # Define corretamente o arquivo de entrada

# Configuração para produção (sem zone_id)
[env.production]
route = "weather.alicinomoura.xyz/*"

